version: '3'

services:

  github-release:
    image: 'github-release'
    build: './src'

  www:
    image: 'tmvdl/projects:justeat'
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'
